# Generated by Django 3.2.21 on 2023-10-08 11:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('event_location', models.TextField(blank=True)),
                ('event_start', models.TimeField(default=django.utils.timezone.now)),
                ('event_end', models.TimeField(default=django.utils.timezone.now)),
                ('contact', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('event_cover', models.ImageField(blank=True, default='../default_post_image_vrz129', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
