# Generated by Django 3.2.21 on 2023-11-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubevents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclubevent',
            name='event_organiser',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
